//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baichday.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Add
    {
        public Add()
        {
            this.Comments = new HashSet<Comment>();
        }
    
        public int Id { get; set; }
        public string title { get; set; }
        public string Price { get; set; }
        public string description { get; set; }
        public string contact { get; set; }
        public string image { get; set; }
        public string category { get; set; }
        public string location { get; set; }
        public Nullable<int> Cid { get; set; }
        public Nullable<int> Aid { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
    }
}
