//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baichday.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.Adds = new HashSet<Add>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string password { get; set; }
        public string Email { get; set; }
    
        public virtual ICollection<Add> Adds { get; set; }
    }
}
